pipeline { 
    agent any  
    environment {
        def mvn = "/home/pi/apache-maven/bin/mvn"
    }
    stages { 
        stage(' Deploy') { 
            steps { 
				sh "rm -rf /home/pi/scbAI/*"
				sh "cp -R ${WORKSPACE}/scbAI/* /home/pi/scbAI"
				sh "rm /home/pi/scbAI/Jenkinsfile"
				sh "rm /home/pi/scbAI/readme.md"
			}
        }
    }
}